# Generated by Django 5.0 on 2024-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
